[package]
name = "annotate-snippets"
version = "0.9.2"
edition = "2021"
rust-version = "1.70.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
description = "Library for building code annotations"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang/annotate-snippets-rs"
readme = "README.md"
keywords = ["code", "analysis", "ascii", "errors", "debug"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
unicode-width = "0.1"
yansi-term = { version = "0.1", optional = true }

[dev-dependencies]
criterion = "0.3"
difference = "2.0"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
yansi-term = "0.1"

[[bench]]
name = "simple"
harness = false

[features]
default = []
color = ["yansi-term"]
